WINDOW_NAME = "Memory Game"
WINDOW_SIZE = (640, 480)
FPS = 60
REVEAL_SPEED = 8
BOX_SIZE = 40
GAP_SIZE = 10
BOARD_WIDTH = 10
BOARD_HEIGHT = 7
X_MARGIN = int((WINDOW_SIZE[0] - (BOARD_WIDTH * (BOX_SIZE + GAP_SIZE))) / 2)
Y_MARGIN = int((WINDOW_SIZE[1] - (BOARD_WIDTH * (BOX_SIZE + GAP_SIZE))) / 2)

assert (BOARD_WIDTH * BOARD_HEIGHT) % 2 == 0, "board area must be even"